In [1]:
import tensorflow as tf

2023-08-05 15:49:18.683655: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-08-05 15:49:19.260176: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-08-05 15:49:19.263475: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-05 15:49:21.478400: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [3]:
#zero dimensional tensor
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [4]:
tensor_one_d = tf.constant([2,0,-3,8,90])
print(tensor_one_d)

tf.Tensor([ 2  0 -3  8 90], shape=(5,), dtype=int32)


In [5]:
tensor_two_d = tf.constant([
                [2,3,4,5],
                [7,8,9,5]
            ])
print(tensor_two_d)

tf.Tensor(
[[2 3 4 5]
 [7 8 9 5]], shape=(2, 4), dtype=int32)


In [6]:
tensor_three_d  = tf.constant([
        [[1,2,3],
        [3,4,5]],

        [[2,3,4],
        [9,8,0]],
        
        [[7,8,9],
        [3,6,4]],

        [[1,2,1],
        [7,5,7]],
        
])

print(tensor_three_d)

tf.Tensor(
[[[1 2 3]
  [3 4 5]]

 [[2 3 4]
  [9 8 0]]

 [[7 8 9]
  [3 6 4]]

 [[1 2 1]
  [7 5 7]]], shape=(4, 2, 3), dtype=int32)


In [7]:
print(tensor_three_d.ndim)

3


In [11]:
tensor_4d = tf.constant([
    [
        [[1, 2, 3], [3, 4, 5]],
        [[2, 3, 4], [9, 8, 0]],
        [[7, 8, 9], [3, 6, 4]],
        [[1, 2, 1], [7, 5, 7]],
    ],
    [
        [[1, 2, 3], [3, 4, 5]],
        [[2, 3, 4], [9, 8, 0]],
        [[7, 8, 9], [3, 6, 4]],
        [[1, 2, 1], [7, 5, 7]],
    ],
    [
        [[1, 2, 3], [3, 4, 5]],
        [[2, 3, 4], [9, 8, 0]],
        [[7, 8, 9], [3, 6, 4]],
        [[1, 2, 1], [7, 5, 7]],
    ],
    [
        [[1, 2, 3], [3, 4, 5]],
        [[2, 3, 4], [9, 8, 0]],
        [[7, 8, 9], [3, 6, 4]],
        [[1, 2, 1], [7, 5, 7]],
    ],
])


In [12]:
tensor_4d.shape

TensorShape([4, 4, 2, 3])

In [14]:
tensor_one_d = tf.constant([2,0,-3,8,90],dtype=tf.float16)
casted_tensor_one_d = tf.cast(tensor_one_d,dtype=tf.bool) #tensorflow typecasting
print(tensor_one_d)
print(casted_tensor_one_d)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float16)
tf.Tensor([ True False  True  True  True], shape=(5,), dtype=bool)


### tensorflow string datatype with 

In [16]:
tensor_string = tf.constant(["Hello world","hy","numpy"])

print(tensor_string)

tf.Tensor([b'Hello world' b'hy' b'numpy'], shape=(3,), dtype=string)


## Numpy , np Array

In [17]:
import numpy as np

In [19]:
np_array = np.array([1,2,3])
print(np_array)

[1 2 3]


In [20]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)


# Creating matrices  using tf.eye api

#### for more information about the api go to [tf.eye](https://www.tensorflow.org/api_docs/python/tf/eye)

In [29]:
eye_tensor = tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape=[2,4],
    dtype=tf.dtypes.float64,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]


 [[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]], shape=(2, 4, 5, 5), dtype=float64)


# Create a tensorflow method fill with scalar value

#### for more information go to [tf.fill](https://www.tensorflow.org/api_docs/python/tf/fill)

In [31]:
fill_tensor = tf.fill(
    [2, 3], 9, name=None

)

print(fill_tensor)


tf.Tensor(
[[9 9 9]
 [9 9 9]], shape=(2, 3), dtype=int32)
